-- ===================================================================
-- Supabase Setup Script for PerspecTEAve Notifications & Push Subscriptions
-- Copy and run this script in your Supabase project's SQL Editor
-- (Dashboard -> SQL Editor -> New query -> Paste & Run)
-- ===================================================================

-- 1. Create notifications table
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    body text NOT NULL,
    read boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anyone (visitors) to insert new notifications
DROP POLICY IF EXISTS "Allow anonymous insert" ON public.notifications;
CREATE POLICY "Allow anonymous insert" ON public.notifications
    FOR INSERT TO anon, authenticated
    WITH CHECK (true);

-- Policy: Only the admin (teaboy27@perspecteave.com) can view/modify notifications
DROP POLICY IF EXISTS "Allow admin full access to notifications" ON public.notifications;
CREATE POLICY "Allow admin full access to notifications" ON public.notifications
    FOR ALL TO authenticated
    USING (auth.jwt() ->> 'email' = 'teaboy27@perspecteave.com');


-- 2. Create push_subscriptions table
CREATE TABLE IF NOT EXISTS public.push_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint text UNIQUE NOT NULL,
    p256dh text NOT NULL,
    auth text NOT NULL,
    user_id text DEFAULT 'teaboy27' NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on push_subscriptions
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anyone (visitors) to select endpoints to send push notifications
DROP POLICY IF EXISTS "Allow anonymous select of subscriptions" ON public.push_subscriptions;
CREATE POLICY "Allow anonymous select of subscriptions" ON public.push_subscriptions
    FOR SELECT TO anon, authenticated
    USING (true);

-- Policy: Only the admin can subscribe, update, or delete subscriptions
DROP POLICY IF EXISTS "Allow admin full access to subscriptions" ON public.push_subscriptions;
CREATE POLICY "Allow admin full access to subscriptions" ON public.push_subscriptions
    FOR ALL TO authenticated
    USING (auth.jwt() ->> 'email' = 'teaboy27@perspecteave.com');
